### ISSUE TITLE
Update `FilterMenu` component to new designs

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-cp-map#36]
## Acceptance Criteria

- [ ] Update existing `FilterMenu` component to new designs ([mobile](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=1329-23360&t=GiD5KJgOJ5K7t9Md-0) and [desktop](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=1187-32851&m=dev))
- [ ] Use `Accordion` component from Streetscape to make filter menu collapesable
- [ ] Update logic for borough dropdown - Current logic is that it is hidden when City Council District district type is selected, new logic is that it remains but is disabled when CCD is selected
- [ ] Collapsable FilterMenu is always shown on mobile - note difference with old design that used "Filter by Geography" button. That button should be removed

### Out of scope
* "About" panel - on [desktop](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=1187-32851&m=dev), the new designs have the "Capital Projects Portal" about info as another accordion section below the filter menu. For this Issue, only implement the filter menu part of that accordion. The about info portion will be added in #6 

### Block by
#28

**Comment by dhochbaum-dcp** [comment]
Ready for QA: https://qa-capitalplanning.nycplanningdigital.com

**Comment by TylerMatteo** [comment]
@wndyli @jessicashanshanhuang This is ready for feedback at that URL ☝ Please self assign and move to "In QA" once you've started testing.

**Comment by jessicashanshanhuang** [comment]
Hey @dhochbaum-dcp! Here's our feedback:
<img src="https://github.com/user-attachments/assets/c1f9080b-5bd8-4620-be15-f39741d1181c" width=40% height=40%>

<img width="1344" alt="Screenshot 2024-07-31 at 5 10 29 PM" src="https://github.com/user-attachments/assets/177bfa95-7d37-4923-bbb7-c4914c8e074a">

In the City Council District Option, for the District Number dropdown:
- If it's possible to show only five options at a time and include a scrollbar to go through the selection, that would be more optimal to keep consistent dropdowns and not have that element expand over the webpage. 
- Also I noticed that the district numbers are not in ascending order and single digit values aren't consistent to how it is displayed in CD option (i.e. "1, 2, 3" vs "01, 02, 03"). For consistency, if we could go with ascending order and double digits display, that would be great.

**Comment by jessicashanshanhuang** [comment]
![Screenshot 2024-08-01 at 1 07 27 PM](https://github.com/user-attachments/assets/0971f278-6b1f-4455-825c-dd6dc0eca54e)

Not a high priority but a good practice is to right aligning all the elements (logo and map navigations buttons) so they all fall under the same column.

**Comment by TangoYankee** [comment]
> If it's possible to show only five options at a time and include a scrollbar to go through the selection, that would be more optimal to keep consistent dropdowns and not have that element expand over the webpage.

I agree this would be an improvement. However, Chakra is wrapping the native browser `select` and `option` tags. This makes it difficult to apply this change. I do think it is worth doing but I would like to break it off into a follow-up ticket.

**Comment by TangoYankee** [comment]
> Also I noticed that the district numbers are not in ascending order and single digit values aren't consistent to how it is displayed in CD option (i.e. "1, 2, 3" vs "01, 02, 03"). For consistency, if we could go with ascending order and double digits display, that would be great.

I'd like to split this comment into two separate problems: 

First, is ordering the results. I agree that ascending order would be better. Implementing this sorting in the frontend should be straightforward. @dhochbaum-dcp would you be okay implementing sorting as part of this ticket? If not we can break it out into a follow-up ticket.

Second, is "double digit" v. "single digit" display. This derives from the data source, rather than an active choice in the frontend. I agree that consistency is better. It is also valuable to hear that "double-digits" would be preferred over "single digits". However, I would prefer to break this out into a ticket for our data processing repository [(ae-data-flow)](https://github.com/NYCPlanning/ae-data-flow/) because this is where are "data doctoring" should happen.

**Comment by TangoYankee** [comment]
> ![Screenshot 2024-08-01 at 1 07 27 PM](https://private-user-images.githubusercontent.com/159487187/354367799-0971f278-6b1f-4455-825c-dd6dc0eca54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTExOTgsIm5iZiI6MTcyMjk1MDg5OCwicGF0aCI6Ii8xNTk0ODcxODcvMzU0MzY3Nzk5LTA5NzFmMjc4LTZiMWYtNDQ1NS04MjVjLWRkNmRjMGVjYTU0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMzI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzA2NzAxNzRkNGNjOTJiZTVmMjhkMzY5MjNhZGY5ZGI1ZGI5ZjRlZGE2NTZiMTk0YzNjOTc5YWI5NDMzZDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6flvDK5kQCtnh3Y2PZ_ns5bwkvAG0Fs-xkGjnEf0DeU)
> 
> Not a high priority but a good practice is to right aligning all the elements (logo and map navigations buttons) so they all fall under the same column.
> 
> ![Screenshot 2024-08-01 at 1 15 32 PM](https://private-user-images.githubusercontent.com/159487187/354370382-4dcedeb8-3f5a-4ca8-bc44-c01fe2d751cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTExOTgsIm5iZiI6MTcyMjk1MDg5OCwicGF0aCI6Ii8xNTk0ODcxODcvMzU0MzcwMzgyLTRkY2VkZWI4LTNmNWEtNGNhOC1iYzQ0LWMwMWZlMmQ3NTFjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxMzI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGY5MGVjNDg2MDg1NmFhYzJiZjViZGRlMGQ4ZTlkMWMyNjY4ZThhMmMyYzdmZGU1MWRkMjliZTVmMmVhOWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uf4NFV_ixyw7Dv88EvVpSfI0zOc2KAUw-w1ISLhIZqM)
> 
> Logo is overlapping the contributions portion when desktop view is minimized.

Yeah, the logo stuff has been a haunting us for awhile. I'll open a ticket to capture this feedback for future iterations.

**Comment by TangoYankee** [comment]
> For mobile, the width of the dropdown should be same size to the selection bar. Currently, the width is smaller.

Is this in reference to this behavior? 

I believe this is how native `option` and `select` work and it is slightly different for every browser. Getting the style consistent would require swapping to a different implementation of the dropdowns.

![dropdown width is smaller than selection box](https://github.com/user-attachments/assets/4e7dda01-de97-44a1-993a-acaf0f904f57)

**Comment by dhochbaum-dcp** [comment]
@TangoYankee @TylerMatteo which are the items I should take care of?
- Logo overlapping the contributions on mobile doesn't make sense to work on right now if we're redoing the whole alignment anyway, and I believe the latest designs have the attribution moved to the info button on mobile
- I can sort the District Number drop-down, but should I use a function that assumes leading zeroes or not?  Might be better to move this into a ticket to take care of once the data flow has been updated

Doesn't seem like there's anything else mentioned to take care of right now.

**Comment by TangoYankee** [comment]
> I can sort the District Number drop-down, but should I use a function that assumes leading zeroes or not? Might be better to move this into a ticket to take care of once the data flow has been updated

Sounds good

**Comment by jessicashanshanhuang** [comment]
> > For mobile, the width of the dropdown should be same size to the selection bar. Currently, the width is smaller.
> 
> Is this in reference to this behavior?
> 
> I believe this is how native `option` and `select` work and it is slightly different for every browser. Getting the style consistent would require swapping to a different implementation of the dropdowns.
> 
> ![dropdown width is smaller than selection box](https://private-user-images.githubusercontent.com/11068062/355481181-4e7dda01-de97-44a1-993a-acaf0f904f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTc5NzEsIm5iZiI6MTcyMjk1NzY3MSwicGF0aCI6Ii8xMTA2ODA2Mi8zNTU0ODExODEtNGU3ZGRhMDEtZGU5Ny00NGExLTk5M2EtYWNhZjBmOTA0ZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE1MjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMGY1MzA0ZjRjOGY2MDJkODcwYzFiNmIyZTIyNjhjODRmNzZmNWY5ZmZlNDVjYWM5YzgwYmFmNWNmOWJiM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8pupwuNJs2PWwpVyCdogD6VFgMGnhA31xi9Kfx28rgI)


Hey @TangoYankee! Yes, I was referring to the placement of the dropdown because there are instances where the placement is centered and in other instances shifted to the left. It could be related to how many options or the text length for an option (option with number values seems more centered versus borough dropdown) are within the dropdown though I am not to sure if that could be the main issue.

**Comment by TangoYankee** [comment]
> which are the items I should take care of?

@dhochbaum-dcp, only the code feedback in PR #48 appears actionable within this ticket. It seems we're moving work on the rest of the feedback to future tickets

**Comment by dhochbaum-dcp** [comment]
Ok, great - that PR is just waiting for approval to be merged.
