### ISSUE TITLE
Add "fly to" functionality for selected capital project

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-cp-map#49]
## Acceptance Criteria
- [ ] When a new capital project is selected and reflected in the route path params, the map should pan and zoom to center on the selected project
- [ ] The entire project should be visible, so pan and zoom should be based on a bounding box around the entire project.
   - **Note** "visibility" should be in reference to the device screen, without regard to the content panels. Accounting for the content panels is non-trivial. We're simplifying this first implementation by ignoring the content panels
- [ ] The logic for updating `viewState` is connected to the router such that if a user clicks between several projects and then uses the browser "back" button, the map will navigate through the projects in the browser history.

## Technical Notes
* This should use the `findCapitalProjectGeoJsonByManagingCodeCapitalProjectId` endpoint to be added in this [Issue](https://github.com/NYCPlanning/ae-zoning-api/issues/342). It will likely make sense to replace the call to `findCapitalProjectByManagingCodeCapitalProjectId` added in #41 with a call to this new API.
* The capital project geojson should be displayed on the map via a newly added [GeoJsonLayer](https://deck.gl/docs/api-reference/layers/geojson-layer) that is displayed on top of the tile layers. The geojson returned by the API can be passed to the `data` prop of the layer.
* Use the GeoJsonLayer to show the selected color for the selected project (this is currently handled in `getFillColor` of the tile layer)
* See this [example](https://deck.gl/docs/api-reference/core/web-mercator-viewport#fitbounds) for guidance on how to fit the `viewState` to bound of a layer
* Should use `FlyToInterpolator` to transition the view state smoothly

## Blocked by
~* https://github.com/NYCPlanning/ae-zoning-api/issues/342~

**Comment by TangoYankee** [comment]
Added note to ignore content panels to implement "bad" "fly-to"
