### ISSUE TITLE
Add Welcome panel with placeholder copy

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ae-cp-map#6]
- [ ] Add responsive Welcome panel with placeholder text per Figma mock ups for [mobile](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=1337-19770&m=dev) and [desktop](https://www.figma.com/design/LYHHoPop9l0jpEivk5CFzJ/Capital-Projects-Portal?node-id=1208-6719&m=dev)
- [ ] Panel has maximum height according to designs and text is scrollable within.
- [ ] On mobile, modal "Drawer" is shown by default on page load but can be toggled via clicking the "info" icon. Use [Chakra `<InfoIcon>`](https://v2.chakra-ui.com/docs/components/icon/usage).

## Blocked by
* #28 
* #36

**Comment by TylerMatteo** [comment]
Blocked by #5

**Comment by pratishta** [comment]
> toggled via clicking the "info" icon
Is this a common way to close and open panels? I imagine that if I saw the welcome message, I'd want to "x" out of the panel rather than think to click on the info icon on the bottom right.

**Comment by TylerMatteo** [comment]
@damonmcc to touch base with designers on status of new designs. Leaning towards going forward with new designs for this.

**Comment by damonmcc** [comment]
@TylerMatteo the figma pages with new mobile designs have been moved from the WIP section to the NEW section. feel free to comment in those pages with feedback/questions!

there are also pages for prototypes of both web and mobile in the NEW section

cc @wndyli, @jessicashanshanhuang

**Comment by dhochbaum-dcp** [comment]
The mobile designs do not reflect the info icon that we currently have in the bottom right corner.  Are we having two info icons with different functionality?
